//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booked_Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booked_Ticket()
        {
            this.Cancelled_Ticket = new HashSet<Cancelled_Ticket>();
        }
    
        public decimal PNR_No { get; set; }
        public decimal User_id { get; set; }
        public decimal Train_No { get; set; }
        public string Passenger_Name { get; set; }
        public int Passenger_Age { get; set; }
        public double TotalFare { get; set; }
        public System.DateTime Booking_Date_Time { get; set; }
    
        public virtual Train_Details Train_Details { get; set; }
        public virtual User_details User_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancelled_Ticket> Cancelled_Ticket { get; set; }
    }
}
