//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RRSysDBEntities : DbContext
    {
        public RRSysDBEntities()
            : base("name=RRSysDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Details> Admin_Details { get; set; }
        public virtual DbSet<Booked_Ticket> Booked_Ticket { get; set; }
        public virtual DbSet<Cancelled_Ticket> Cancelled_Ticket { get; set; }
        public virtual DbSet<Train_Details> Train_Details { get; set; }
        public virtual DbSet<User_details> User_details { get; set; }
        public virtual DbSet<Class_Fare> Class_Fare { get; set; }
        public virtual DbSet<Seat_Availability> Seat_Availability { get; set; }
    
        public virtual int SeatManageProc(Nullable<decimal> trainNo, Nullable<int> @class)
        {
            var trainNoParameter = trainNo.HasValue ?
                new ObjectParameter("TrainNo", trainNo) :
                new ObjectParameter("TrainNo", typeof(decimal));
    
            var classParameter = @class.HasValue ?
                new ObjectParameter("Class", @class) :
                new ObjectParameter("Class", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SeatManageProc", trainNoParameter, classParameter);
        }
    }
}
