//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat_Availability
    {
        public int Serial_No { get; set; }
        public decimal Train_No { get; set; }
        public int C1_A { get; set; }
        public int C2_A { get; set; }
        public int C3_A { get; set; }
        public int SL { get; set; }
    
        public virtual Train_Details Train_Details { get; set; }
    }
}
